//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMK_Toolbox.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("QMK_Toolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        public static string Menu_FileOpen {
            get {
                return ResourceManager.GetString("Menu_FileOpen", resourceCulture);
            }
        }
        
        public static string Menu_FileExit {
            get {
                return ResourceManager.GetString("Menu_FileExit", resourceCulture);
            }
        }
        
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        public static string Menu_ToolsFlash {
            get {
                return ResourceManager.GetString("Menu_ToolsFlash", resourceCulture);
            }
        }
        
        public static string Menu_ToolEeprom {
            get {
                return ResourceManager.GetString("Menu_ToolEeprom", resourceCulture);
            }
        }
        
        public static string Menu_ToolExitDFU {
            get {
                return ResourceManager.GetString("Menu_ToolExitDFU", resourceCulture);
            }
        }
        
        public static string Menu_ToolAutoFlash {
            get {
                return ResourceManager.GetString("Menu_ToolAutoFlash", resourceCulture);
            }
        }
        
        public static string Menu_ToolShowAll {
            get {
                return ResourceManager.GetString("Menu_ToolShowAll", resourceCulture);
            }
        }
        
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        public static string Menu_HelpCheckNew {
            get {
                return ResourceManager.GetString("Menu_HelpCheckNew", resourceCulture);
            }
        }
        
        public static string Menu_HelpAbout {
            get {
                return ResourceManager.GetString("Menu_HelpAbout", resourceCulture);
            }
        }
        
        public static string Label_LocalFile {
            get {
                return ResourceManager.GetString("Label_LocalFile", resourceCulture);
            }
        }
        
        public static string Label_MCU {
            get {
                return ResourceManager.GetString("Label_MCU", resourceCulture);
            }
        }
        
        public static string Button_Open {
            get {
                return ResourceManager.GetString("Button_Open", resourceCulture);
            }
        }
        
        public static string Label_AutoFlash {
            get {
                return ResourceManager.GetString("Label_AutoFlash", resourceCulture);
            }
        }
        
        public static string Button_Flash {
            get {
                return ResourceManager.GetString("Button_Flash", resourceCulture);
            }
        }
        
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        public static string Button_ExitDFU {
            get {
                return ResourceManager.GetString("Button_ExitDFU", resourceCulture);
            }
        }
        
        public static string NoHID {
            get {
                return ResourceManager.GetString("NoHID", resourceCulture);
            }
        }
        
        public static string Menu_ToolsKeyTester {
            get {
                return ResourceManager.GetString("Menu_ToolsKeyTester", resourceCulture);
            }
        }
    }
}
