typedef enum BootloaderType : NSUInteger {
    BootloaderTypeAPM32DFU,
    BootloaderTypeAtmelDFU,
    BootloaderTypeAtmelSAMBA,
    BootloaderTypeAVRISP,
    BootloaderTypeBootloadHID,
    BootloaderTypeCaterina,
    BootloaderTypeHalfKay,
    BootloaderTypeKiibohdDFU,
    BootloaderTypeLUFAHID,
    BootloaderTypeLUFAMS,
    BootloaderTypeQMKDFU,
    BootloaderTypeQMKHID,
    BootloaderTypeSTM32DFU,
    BootloaderTypeSTM32Duino,
    BootloaderTypeUSBAsp,
    BootloaderTypeUSBTinyISP,
    BootloaderTypeWB32DFU,
    BootloaderTypeNone
} BootloaderType;
